# Functions to make barodes (data matrix, QR code, and code128)
#' dmcode_make: create a grid Grob object for drawing data matrix code generated by function "dmcode"
#' @export
#' @param scale 0-1 barcode scaling inside the drawing area
dmcode_make<-function(Labels, square=1, scale=1){
  # Create text label
  # Xtxt<-gsub("_", "-", Labels)
  Xtxt <- Labels
  if(nchar(Xtxt) < 1){
    Xtxt <- paste0("  ", Xtxt)
    warning("Label is blank. Padding with empty spaces.")
  }
  # Create qrcode
  Xpng <- grid::rasterGrob(
    dmcode(paste0(Xtxt), square), width=scale, height = scale,
    interpolate = FALSE)
  return(Xpng)
}

#' qrcode_make: create a grid Grob object for drawing QR code generated by function "qr"
#' @export
qrcode_make<-function(Labels, ErrCorr=2, scale=1){
  # Create text label
  # Xtxt<-gsub("_", "-", Labels)
  Xtxt <- Labels
  if(nchar(Xtxt) < 1){
    Xtxt <- paste0("  ", Xtxt)
    warning("Label is blank. Padding with empty spaces.")
  }
  # Create qrcode
  Xpng <- grid::rasterGrob(
    qrcode(paste0(Xtxt), ecl = ErrCorr), width=scale, height = scale,
    interpolate = FALSE)
  return(Xpng)
}

#' code_128_make: create a grid Grob object for drawing linear code128
#' @export
code_128_make <- function(Labels){
  ## labels is a character string
  ## read in dict 
  Barcodes <- barcodes128
  ## double check Labels
  Labels <- as.character(Labels)
  Labels <- iconv(Labels, from = "utf-8", to = "ascii", sub = "-")
  start_code <- 209
  lab_chars <- unlist(strsplit(Labels, split = ""))
  lab_values <- sapply(lab_chars, function(x) utf8ToInt(x))
  # ascii to code 128 is just a difference of 32, this line keeps clarity
  code_values <- lab_values - 32
  # 104 is the start value for start code b, hardcoded right now
  check_sum <- 104 + sum(code_values * seq(1,length(code_values)))
  check_character <- check_sum %% 103
  Binary_code <- sapply(lab_values, 
                        function(x, Barcodes) Barcodes$Barcode[x == Barcodes$ASCII], 
                        Barcodes = Barcodes)
  ## create quiet zone
  quiet_zone <- paste(c(1:(10)*0),collapse="")
  ## paste together in order: quiet zone, start code binary, binary label, checksum character
  ## stop code, and quiet zone. Barcode for checksum is extracted based on position in Barcodes.
  binary_label <- paste(quiet_zone, 
                        Barcodes$Barcode[Barcodes$ASCII == start_code],
                        paste(Binary_code, collapse=""),
                        Barcodes$Barcode[check_character + 1],
                        "1100011101011",
                        quiet_zone,
                        collapse = "", sep ="")
  ## split binary apart for 
  bar_values <- as.numeric(unlist(strsplit(binary_label, split = "")))
  barcode_bars <- grid::rasterGrob(t(!as.matrix(bar_values)), width = 1, height = 1, interpolate = FALSE)
  return(barcode_bars)
}
